name: Check links

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - "data/projects.json"
      - ".github/workflows/links.yml"
  schedule:
    - cron: "17 3 * * 1"
  pull_request:
    paths:
      - "**/*.md"
      - "data/projects.json"
      - ".github/workflows/links.yml"

permissions:
  contents: read

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Markdown links
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --accept 200,206,429
            --exclude '^https://www[.]patreon[.]com/infernoplus/posts/halocraft-73930239            "./**/*.md"
            "./data/projects.json"
          fail: true

            --exclude '^https://www[.]patreon[.]com/infernoplus/posts/dark-souls-90413873            "./**/*.md"
            "./data/projects.json"
          fail: true

            --exclude '^https://www[.]patreon[.]com/infernoplus/posts/dark-souls-46865100            "./**/*.md"
            "./data/projects.json"
          fail: true

            --exclude '^https://www[.]reddit[.]com/r/GTAV/comments/1wuppva/somebody_modded_minecraft_into_gta_5/            "./**/*.md"
            "./data/projects.json"
          fail: true

            --exclude '^https://heldgames[.]com/guides/is-that-viral-mod-video-real            "./**/*.md"
            "./data/projects.json"
          fail: true

            "./**/*.md"
            "./data/projects.json"
          fail: true
